name: CI / CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow only on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The machine type to run the workflow on
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build Phase: Build the Docker image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t my-docker-app:latest .

      # Test Phase: Run the container and execute tests inside it
      - name: Run Container and Execute Tests
        run: docker run --rm my-docker-app:latest ./run-tests.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # The deploy job will only run if build-and-test succeeds
    if: github.ref == 'refs/heads/main'  # Run deploy only for the main branch
    steps:
      # Checkout the repository code again (required for deployment)
      - name: Checkout Code
        uses: actions/checkout@v2

      # Deployment Phase: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Tag the built image for Docker Hub
      - name: Tag Docker Image
        run: docker tag my-docker-app:latest mydockerhubuser/my-docker-app:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push mydockerhubuser/my-docker-app:latest

      # (Optional) Deploy to Kubernetes using your deployment manifests
      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml
