name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-docker-app:latest .

      - name: Save Docker image to file
        run: docker save my-docker-app:latest -o my-docker-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-docker-app.tar

      - name: Run Container and Execute Tests
        run: docker run --rm my-docker-app:latest ./run-tests.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image from file
        run: docker load -i my-docker-app.tar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag Docker Image
        run: docker tag my-docker-app:latest ayazid/my-docker-app:latest

      - name: Push Docker Image
        run: docker push ayazid/my-docker-app:latest
